# Generated by Django 4.2.1 on 2023-09-02 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_followed_users_post_user_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_users',
            field=models.ManyToManyField(blank=True, related_name='following_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='users_liked', to='network.post'),
        ),
    ]
